### ISSUE TITLE
Defining duration for calculation

### ISSUE THREAD

**Issue by limsokneth** [PratyushTripathy/global_flood_mapper#1]
Dear Pratyush,

I'd like to ask for your clarification on setting dates for this calculation. 
For example flood in Cambodia: 
Pre flood date: 01 Apr 2020 + 60 days
During flood date: 17 Oct 2020 + 8 days
From my understanding, the satellite images recorded between 01 Apr and 31 May 2020 were used for pre-flood calculation
                                         and satellite images recorded between 17 Oct and 25 Oct were used for during flood calculation. 
So, May I know whether what I understand is correct or not? if not, can you please clarify this point? 
Your help is greatly appreciated. I look forward to hearing from you.

With best regards, 
Sokneth

**Comment by PratyushTripathy** [comment]
Yes, you got the logic right. Besides, you can first try generating flood map for a large area to get some sense of where floods happened. But eventually, if you could focus on smaller scale floods (captured by a single date scene), you have better chances if capturing the peak. If you really want to map large area floods, it is totally fine, it's just that you will have to use a larger time frame for during floods scenes.

**Comment by limsokneth** [comment]
Very much appreciated your comprehensive explanation.
